<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Version>1.2.1</Version>
    <Company>Forward-Back Hourglass</Company>
    <Product>Forward-Back Hourglass</Product>
  </PropertyGroup>
</Project>
